# Site settings
title: Mappings
email: cps232@cornell.edu
description: > # this means to ignore newlines until "baseurl:"
  In which I work through problems and write explorable explanations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://christosilvia.github.io" # the base hostname & protocol for your site
twitter_username: ChristoSilvia
github_username:  ChristoSilvia

# Build settings
markdown: kramdown

gems:
 - jekyll-feed

#Liquid-LaTeX plugin
#liquid_latex:
#        debug: false
#        density: 300
#        usepackages: pst-all, pst-3dplot
#        output_directory: /res/latex
#        latex_cmd: "latex -interaction=nonstopmode $texfile &> /dev/null"
#        dvips_cmd: "dvips -E $dvifile -o $epsfile &> /dev/null"
#        convert_cmd: "convert -density $density $epsfile $pngfile &> /dev/null"
#        temp_filename: "latex/temp"

